name: Enforce License Compliance

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  enforce-license-compliance:
    if: github.repository_owner == 'getsentry'
    runs-on: self-hosted
    steps:
      - name: 'Enforce License Compliance'
        uses: getsentry/action-enforce-license-compliance@main
        with:
          fossa_api_key: ${{ secrets.FOSSA_API_KEY }}
